from collections.abc import AsyncIterator, Awaitable
from typing import Any, Protocol


class AnyPaginator(Protocol):
    def paginate(self, **_kwargs: object) -> "AnyAsyncIterator": ...


class AnyAsyncIterator(Protocol):
    def __aiter__(self) -> "AnyAsyncIterator": ...
    async def __anext__(self) -> dict[str, Any]: ...


class S3Client(Protocol):
    @property
    def exceptions(self) -> Any: ...

    async def get_object(self, _Bucket: str, _Key: str, **_kwargs: object) -> dict[str, object]: ...
    async def head_object(
        self, _Bucket: str, _Key: str, **_kwargs: object
    ) -> dict[str, object]: ...
    async def put_object(
        self, _Bucket: str, _Key: str, _Body: object, **_kwargs: object
    ) -> dict[str, object]: ...
    async def delete_object(
        self, _Bucket: str, _Key: str, **_kwargs: object
    ) -> dict[str, object]: ...
    async def list_objects_v2(
        self, _Bucket: str, _Prefix: str = "", **_kwargs: object
    ) -> dict[str, object]: ...
    async def copy_object(
        self,
        _Bucket: str,
        _CopySource: dict[str, str],
        _Key: str,
        _MetadataDirective: str | None = None,
        _ContentType: str | None = None,
        **_kwargs: object,
    ) -> dict[str, object]: ...
    async def upload_file(
        self, _Filename: str, _Bucket: str, _Key: str, **_kwargs: object
    ) -> None: ...
    async def upload_fileobj(
        self, _Fileobj: object, _Bucket: str, _Key: str, **_kwargs: object
    ) -> None: ...
    async def download_fileobj(
        self, _Bucket: str, _Key: str, _Fileobj: object, **_kwargs: object
    ) -> None: ...
    async def generate_presigned_url(
        self,
        _ClientMethod: str,
        _Params: dict[str, object] | None = None,
        _ExpiresIn: int = 3600,
        _HttpMethod: str | None = None,
    ) -> str: ...
    async def create_multipart_upload(
        self, _Bucket: str, _Key: str, **_kwargs: object
    ) -> dict[str, object]: ...
    async def upload_part(
        self,
        _Bucket: str,
        _Key: str,
        _PartNumber: int,
        _UploadId: str,
        _Body: object,
        **_kwargs: object,
    ) -> dict[str, object]: ...
    async def complete_multipart_upload(
        self,
        _Bucket: str,
        _Key: str,
        _UploadId: str,
        _MultipartUpload: dict[str, object],
        **_kwargs: object,
    ) -> dict[str, object]: ...
    async def abort_multipart_upload(
        self, _Bucket: str, _Key: str, _UploadId: str, **_kwargs: object
    ) -> dict[str, object]: ...
    def get_paginator(self, _operation_name: str) -> "AnyPaginator": ...
    async def __aenter__(self) -> "S3Client": ...
    async def __aexit__(self, _exc_type: object, _exc_val: object, _exc_tb: object) -> None: ...
    async def close(self) -> None: ...


class RedisProtocol(Protocol):
    async def get(self, key: str) -> str | None: ...
    async def set(
        self, key: str, value: str, _ex: int | None = None, _nx: bool = False
    ) -> bool | None: ...
    async def hset(
        self,
        name: str,
        key: str | None = None,
        value: str | None = None,
        mapping: dict[str, str] | None = None,
    ) -> int: ...
    async def hgetall(self, name: str) -> dict[bytes, bytes]: ...
    async def expire(self, name: str, time: int) -> bool: ...
    async def incr(self, name: str, _amount: int = 1) -> int: ...
    async def decr(self, name: str, _amount: int = 1) -> int: ...
    async def delete(self, *names: str) -> int: ...
    async def sadd(self, name: str, *values: str) -> int: ...
    async def srem(self, name: str, *values: str) -> int: ...
    async def lrange(self, name: str, start: int, _end: int) -> list[str]: ...
    async def llen(self, name: str) -> int: ...
    async def zadd(self, name: str, mapping: dict[str, float]) -> int: ...
    async def zrem(self, name: str, *values: str) -> int: ...
    async def zcard(self, name: str) -> int: ...
    async def zremrangebyscore(self, name: str, min: str | float, max: str | float) -> int: ...
    def execute_command(self, *_args: str | int | float) -> Awaitable[str | bytes | int | None]: ...
    def pubsub(self) -> "PubSubProtocol": ...


class PubSubProtocol(Protocol):
    async def subscribe(self, *_channels: str) -> None: ...
    async def unsubscribe(self, *_channels: str) -> None: ...
    async def reset(self) -> None: ...
    def listen(self) -> AsyncIterator[dict[str, str | bytes]]: ...
