from __future__ import annotations

import asyncio
import dataclasses
import logging
import uuid
from collections.abc import AsyncGenerator, Awaitable
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any, cast

from arq.connections import ArqRedis, RedisSettings, create_pool
from redis.asyncio import Redis
from redis.asyncio.retry import Retry
from redis.backoff import ExponentialBackoff
from redis.exceptions import BusyLoadingError
from redis.exceptions import ConnectionError as RedisConnectionError
from redis.exceptions import TimeoutError as RedisTimeoutError

from app.config import settings

logger = logging.getLogger(__name__)

type RedisClient = Redis[str]


# Custom Concurrency Exceptions (inherit from TimeoutError for backward compatibility)
class RedisConcurrencyError(TimeoutError):
    """Base exception for Redis concurrency operations."""


class RedisLockTimeoutError(RedisConcurrencyError):
    """Raised when acquiring a distributed lock times out."""


class RedisSemaphoreTimeoutError(RedisConcurrencyError):
    """Raised when acquiring a distributed semaphore times out."""


class RedisSemaphoreUnavailableError(RedisConcurrencyError):
    """Raised when Redis cannot answer a semaphore operation promptly."""


# Retry policy for transient Redis errors (BGSAVE latency spikes, brief network blips)
_REDIS_RETRY = Retry(ExponentialBackoff(cap=10, base=1.0), retries=6)
_REDIS_RETRY_ERRORS: list[type[Exception]] = [
    RedisConnectionError,
    RedisTimeoutError,
    BusyLoadingError,
]

_LUA_DIR = Path(__file__).parent / "lua"
_SEMAPHORE_LUA_SCRIPT = (_LUA_DIR / "semaphore.lua").read_text(encoding="utf-8")


def build_redis_settings() -> RedisSettings:
    """Return arq RedisSettings with resilient connection and retry config."""
    base = RedisSettings.from_dsn(settings.redis_url)
    return dataclasses.replace(
        base,
        conn_timeout=10,
        conn_retries=10,
        conn_retry_delay=2,
        retry_on_timeout=True,
        retry_on_error=_REDIS_RETRY_ERRORS,
        retry=_REDIS_RETRY,
    )


redis_client: RedisClient = Redis.from_url(
    settings.redis_url,
    decode_responses=True,
    retry_on_timeout=True,
    retry_on_error=cast(Any, _REDIS_RETRY_ERRORS),
    retry=_REDIS_RETRY,
)
arq_pool: ArqRedis | None = None

# Pre-registered Lua scripts (EVALSHA execution)
_semaphore_script = redis_client.register_script(_SEMAPHORE_LUA_SCRIPT)


async def get_redis() -> AsyncGenerator[RedisClient, None]:
    yield redis_client


async def close_redis_client() -> None:
    """Close global redis connection pool gracefully."""
    await cast(Any, redis_client).aclose()


async def init_arq_pool() -> None:
    global arq_pool
    arq_pool = await create_pool(build_redis_settings())


async def close_arq_pool() -> None:
    global arq_pool
    if arq_pool:
        await arq_pool.close()
        arq_pool = None


def _is_internal_lease_cancellation(exc: asyncio.CancelledError, token: object) -> bool:
    """Return whether *exc* was generated by our lease-renewal task."""
    return bool(exc.args) and exc.args[0] is token


def _consume_current_cancellation() -> None:
    """Consume one delivered cancellation while cleanup is deferred."""
    task = asyncio.current_task()
    if task is not None and task.cancelling():
        task.uncancel()


def _consume_pending_external_cancellations(
    *, token_was_consumed: bool, external: asyncio.CancelledError | None
) -> asyncio.CancelledError | None:
    """Drain queued cancellation requests and remember external cancellation.

    Renewal issues exactly one tagged cancellation. Any remaining cancellation
    count after consuming that request came from the caller and must be restored
    after ownership cleanup finishes.
    """
    task = asyncio.current_task()
    if task is None:
        return external
    if token_was_consumed:
        while task.cancelling():
            task.uncancel()
            external = external or asyncio.CancelledError()
    return external


async def _await_lease_cleanup[ResultT](
    awaitable: Awaitable[ResultT],
    *,
    internal_cancel_token: object,
) -> tuple[ResultT | None, BaseException | None, asyncio.CancelledError | None]:
    """Finish lease cleanup despite cancellation and report all outcomes."""
    task = asyncio.ensure_future(awaitable)
    external_cancellation: asyncio.CancelledError | None = None

    while not task.done():
        try:
            await asyncio.shield(task)
        except asyncio.CancelledError as exc:
            current = asyncio.current_task()
            if task.done() and task.cancelled() and (current is None or current.cancelling() == 0):
                # The cleanup child was intentionally cancelled; the owner was not.
                break
            if not _is_internal_lease_cancellation(exc, internal_cancel_token):
                external_cancellation = external_cancellation or exc
            _consume_current_cancellation()
        except BaseException:
            # The child task's result is inspected below so cleanup failures can
            # never escape before body/cancellation precedence is decided.
            break

    try:
        result = task.result()
    except BaseException as exc:
        return None, exc, external_cancellation
    return result, None, external_cancellation


@asynccontextmanager
async def redis_lock(
    redis: RedisClient,
    lock_name: str,
    timeout: float = 10.0,
    retry_interval: float = 0.1,
    expire: float = 30,
) -> AsyncGenerator[None, None]:
    """Distributed lock with renewal and cancellation-safe ownership cleanup."""
    if timeout <= 0 or retry_interval <= 0 or expire <= 0:
        raise ValueError("Lock timeout, retry interval, and expiry must be positive")

    lock = redis.lock(f"lock:{lock_name}", timeout=expire, sleep=retry_interval)
    acquired = await lock.acquire(blocking_timeout=timeout)
    if not acquired:
        raise RedisLockTimeoutError(f"Could not acquire lock {lock_name} within {timeout}s")

    renewal_error: BaseException | None = None
    owner_task = asyncio.current_task()
    internal_cancel_token = object()

    async def _renew() -> None:
        nonlocal renewal_error
        try:
            while True:
                await asyncio.sleep(max(expire / 3, 0.01))
                async with asyncio.timeout(1.0):
                    extended = await lock.extend(expire, replace_ttl=True)
                if not extended:
                    raise RedisConcurrencyError(f"Lost lock lease for {lock_name}")
        except asyncio.CancelledError:
            raise
        except BaseException as exc:
            renewal_error = exc
            if owner_task is not None:
                owner_task.cancel(internal_cancel_token)

    renewal_task = asyncio.create_task(_renew())
    body_error: BaseException | None = None
    external_cancellation: asyncio.CancelledError | None = None
    internal_cancel_consumed = False

    try:
        try:
            yield
        except asyncio.CancelledError as exc:
            if _is_internal_lease_cancellation(exc, internal_cancel_token):
                internal_cancel_consumed = True
            else:
                external_cancellation = exc
            _consume_current_cancellation()
        except BaseException as exc:
            body_error = exc
    finally:
        external_cancellation = _consume_pending_external_cancellations(
            token_was_consumed=internal_cancel_consumed,
            external=external_cancellation,
        )

        renewal_task.cancel()
        _, renewal_cleanup_error, cleanup_cancel = await _await_lease_cleanup(
            renewal_task, internal_cancel_token=internal_cancel_token
        )
        if renewal_cleanup_error is not None and not isinstance(
            renewal_cleanup_error, asyncio.CancelledError
        ):
            logger.warning(
                "Lock renewal task cleanup failed for %s: %s",
                lock_name,
                renewal_cleanup_error,
            )
        external_cancellation = external_cancellation or cleanup_cancel

        async def _release() -> None:
            async with asyncio.timeout(1.0):
                await lock.release()

        _, release_error, release_cancel = await _await_lease_cleanup(
            _release(), internal_cancel_token=internal_cancel_token
        )
        external_cancellation = external_cancellation or release_cancel
        if release_error is not None:
            logger.warning(
                "Lock '%s' release encountered error or was already expired before cleanup: %s",
                lock_name,
                release_error,
            )

    if body_error is not None:
        raise body_error
    if external_cancellation is not None:
        raise external_cancellation
    if renewal_error is not None:
        raise RedisConcurrencyError(f"Lost lock lease for {lock_name}") from renewal_error
    if release_error is not None:
        raise RedisConcurrencyError(f"Lost lock ownership for {lock_name}") from release_error


@asynccontextmanager
async def redis_semaphore(
    redis: RedisClient,
    sem_name: str,
    limit: int,
    timeout: float = 60.0,
    retry_interval: float = 0.2,
    expire: float = 300,
) -> AsyncGenerator[None, None]:
    """Distributed semaphore with strict lease-loss and cleanup semantics."""
    if limit < 1:
        raise ValueError("Semaphore limit must be at least 1")
    if timeout <= 0 or retry_interval <= 0 or expire <= 0:
        raise ValueError("Semaphore timeout, retry interval, and expiry must be positive")

    sem_key = f"sem:{sem_name}"
    holder_id = f"{settings.environment}:{uuid.uuid4()}"
    expire_ms = max(1, int(expire * 1000))

    async def _run_script(op: str = "acquire") -> int:
        try:
            async with asyncio.timeout(1.0):
                result = await _semaphore_script(
                    keys=[sem_key],
                    args=[limit, holder_id, op, 0, expire_ms],
                    client=redis,
                )
        except (RedisConnectionError, RedisTimeoutError, BusyLoadingError, TimeoutError) as exc:
            raise RedisSemaphoreUnavailableError(
                f"Redis unavailable while running semaphore operation for {sem_name}"
            ) from exc
        return int(result)

    try:
        async with asyncio.timeout(timeout):
            while True:
                if await _run_script("acquire") == 1:
                    break
                retry_factor = 0.75 + 0.5 * ((hash(holder_id) % 100) / 100.0)
                await asyncio.sleep(retry_interval * retry_factor)
    except RedisConcurrencyError:
        raise
    except TimeoutError:
        raise RedisSemaphoreTimeoutError(
            f"Could not acquire semaphore {sem_name} within {timeout}s"
        ) from None

    renewal_error: BaseException | None = None
    owner_task = asyncio.current_task()
    internal_cancel_token = object()

    async def _renew() -> None:
        nonlocal renewal_error
        try:
            while True:
                await asyncio.sleep(max(expire / 3, 0.01))
                if await _run_script("renew") != 1:
                    raise RedisConcurrencyError(f"Lost semaphore lease for {sem_name}")
        except asyncio.CancelledError:
            raise
        except BaseException as exc:
            renewal_error = exc
            if owner_task is not None:
                owner_task.cancel(internal_cancel_token)

    renewal_task = asyncio.create_task(_renew())
    body_error: BaseException | None = None
    external_cancellation: asyncio.CancelledError | None = None
    internal_cancel_consumed = False

    try:
        try:
            yield
        except asyncio.CancelledError as exc:
            if _is_internal_lease_cancellation(exc, internal_cancel_token):
                internal_cancel_consumed = True
            else:
                external_cancellation = exc
            _consume_current_cancellation()
        except BaseException as exc:
            body_error = exc
    finally:
        external_cancellation = _consume_pending_external_cancellations(
            token_was_consumed=internal_cancel_consumed,
            external=external_cancellation,
        )

        renewal_task.cancel()
        _, renewal_cleanup_error, cleanup_cancel = await _await_lease_cleanup(
            renewal_task, internal_cancel_token=internal_cancel_token
        )
        if renewal_cleanup_error is not None and not isinstance(
            renewal_cleanup_error, asyncio.CancelledError
        ):
            logger.warning(
                "Semaphore renewal task cleanup failed for %s: %s",
                sem_name,
                renewal_cleanup_error,
            )
        external_cancellation = external_cancellation or cleanup_cancel

        async def _release() -> int:
            async with asyncio.timeout(1.0):
                return int(await redis.zrem(sem_key, holder_id))

        removed, cleanup_error, release_cancel = await _await_lease_cleanup(
            _release(), internal_cancel_token=internal_cancel_token
        )
        external_cancellation = external_cancellation or release_cancel
        if cleanup_error is None and removed != 1:
            cleanup_error = RedisConcurrencyError(
                f"Lost semaphore lease for {sem_name} before release"
            )
        elif cleanup_error is not None:
            logger.warning(
                "Failed to remove semaphore holder '%s' from '%s' during cleanup: %s",
                holder_id,
                sem_key,
                cleanup_error,
            )
            cleanup_error = RedisSemaphoreUnavailableError(
                f"Redis unavailable while releasing semaphore {sem_name}"
            )

    if body_error is not None:
        raise body_error
    if external_cancellation is not None:
        raise external_cancellation
    if renewal_error is not None:
        raise RedisConcurrencyError(f"Lost semaphore lease for {sem_name}") from renewal_error
    if cleanup_error is not None:
        raise cleanup_error
