"""Structured error code enum for the upload pipeline."""

from enum import StrEnum

__all__ = ["UploadErrorCode"]


class UploadErrorCode(StrEnum):
    # File validation errors
    FILE_TOO_LARGE = "ERR_FILE_TOO_LARGE"
    FILENAME_TOO_LONG = "ERR_FILENAME_TOO_LONG"
    TYPE_NOT_ALLOWED = "ERR_TYPE_NOT_ALLOWED"
    MIME_MISMATCH = "ERR_MIME_MISMATCH"

    # SVG-specific
    SVG_MALFORMED = "ERR_SVG_MALFORMED"
    SVG_UNSAFE = "ERR_SVG_UNSAFE"

    # Scanning
    MALWARE_DETECTED = "ERR_MALWARE_DETECTED"
    SCAN_UNAVAILABLE = "ERR_SCAN_UNAVAILABLE"

    # Quota / rate limiting
    QUOTA_EXCEEDED = "ERR_QUOTA_EXCEEDED"

    # Intent / idempotency
    INTENT_EXPIRED = "ERR_INTENT_EXPIRED"
    INTENT_MISMATCH = "ERR_INTENT_MISMATCH"

    # Deduplication
    DUPLICATE = "ERR_DUPLICATE"

    # Generic processing failure
    PROCESSING_FAILED = "ERR_PROCESSING_FAILED"

    # tus-specific
    TUS_INVALID_OFFSET = "ERR_TUS_INVALID_OFFSET"
    TUS_UPLOAD_NOT_FOUND = "ERR_TUS_UPLOAD_NOT_FOUND"
    TUS_CONTENT_TYPE = "ERR_TUS_CONTENT_TYPE"
    TUS_CHUNK_TOO_SMALL = "ERR_TUS_CHUNK_TOO_SMALL"
    TUS_CHUNK_TOO_LARGE = "ERR_TUS_CHUNK_TOO_LARGE"
    TUS_CHECKSUM_MISMATCH = "ERR_TUS_CHECKSUM_MISMATCH"
    TUS_CONCURRENCY_LIMIT = "ERR_TUS_CONCURRENCY_LIMIT"
    STORAGE_FULL = "ERR_STORAGE_FULL"

    # Batch-zip errors
    INVALID_ZIP = "ERR_INVALID_ZIP"
    ZIP_BOMB = "ERR_ZIP_BOMB"
    BATCH_TOO_LARGE = "ERR_BATCH_TOO_LARGE"
